
use strict;
use warnings;

use Module::Build 0.3601;


my %module_build_args = (
  "build_requires" => {
    "Module::Build" => "0.3601",
    "Perinci::Sub::DepChecker" => "0.07",
    "Test::More" => "0.96"
  },
  "configure_requires" => {
    "Module::Build" => "0.3601"
  },
  "dist_abstract" => "Depend on a Perl module",
  "dist_author" => [
    "Steven Haryanto <stevenharyanto\@gmail.com>"
  ],
  "dist_name" => "Perinci-Sub-Dep-pm",
  "dist_version" => "0.28",
  "license" => "perl",
  "module_name" => "Perinci::Sub::Dep::pm",
  "recommends" => {},
  "recursive_test_files" => 1,
  "requires" => {
    "Perinci::Util" => 0,
    "Rinci" => "v1.1.22",
    "Sort::Versions" => 0,
    "perl" => "5.010001"
  },
  "script_files" => []
);


my $build = Module::Build->new(%module_build_args);

$build->create_build_script;
